version: '3.8'
services:
  pywordle:
    build: .
    container_name: pywordle-fastapi
    environment:
      PROJECT_ENV: production
      PORT: 8080
      WORDS_API_KEY: "${WORDS_API_KEY}"
      USER_POOL_ID: "${USER_POOL_ID}"
      APP_CLIENT_ID: "${APP_CLIENT_ID}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - .:/usr/src/pywordle/app
    ports:
      - "8080:8080"