version: '3.8'
services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -cors '*'"
  pywordle:
    build: .
    container_name: pywordle-fastapi
    environment:
      PROJECT_ENV: development
      PORT: 8080
      WORDS_API_KEY: "${WORDS_API_KEY}"
      USER_POOL_ID: "${USER_POOL_ID}"
      APP_CLIENT_ID: "${APP_CLIENT_ID}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    depends_on:
      - dynamodb
    volumes:
      - .:/usr/src/pywordle/app
    ports:
      - "8080:8080"